### ISSUE TITLE
Main page references lex75

### ISSUE THREAD

**Issue by Fliptron** [bug400/capasm#1]
This is a wonderful new addition to the HP-85 world!

The main pages references a lex75 directory that holds an example source. This does not currently exist.

As a HP-85 user, I would really appreciate an HP-85 example source and command line example. Maybe one of the system ROMs that you used to verify the assembler.

**Comment by bug400** [comment]
I updated the documentation with a more detailed description of the command line parameters and added some more examples of use. There directories lex75 and lex85 include sample lex source files.

**Comment by Fliptron** [comment]
Thanks.
