### ISSUE TITLE
Some E_RELJUMP_TOOLARGE are not flagged as errors

### ISSUE THREAD

**Issue by maushammer** [bug400/capasm#2]
Great work, thanks!!  I'm writing a large routine and accidentally tried a forward branch that was ~ +200 bytes.  This compiled fine, but ran erratically because the range of branches is -128 to +127  ([reference here](https://groups.io/g/hpseries80/wiki/1851); couldn't find in HP87 assembler manual).

I suggest changing capcommon.py lines 1704-1709 from:
>            offset=value-(self.__pc__+2)
>            if offset < 0:
>               offset=255 -abs(offset)+1
>            if offset > 255 or offset < 0:
>               offset=0
>               self.addError(MESSAGE.E_RELJUMP_TOOLARGE)
(you can see how an offset of +200 is allowed because it's assumed it's a negative number)

To:
>            offset=value-(self.__pc__+2)
>            if offset > 127 or offset < -128:
>               offset=0
>               self.addError(MESSAGE.E_RELJUMP_TOOLARGE)
>            if offset < 0:
>               offset=255 -abs(offset)+1

Awesome work - thank you for this compiler!!

**Comment by bug400** [comment]
Thank You very much for the bug report! I'll check in your fix when the changes for the next commit are finished.

**Comment by bug400** [comment]
Fixed in repository.

**Comment by bug400** [comment]
Fixed in release.
